version: "3.4"
services:
  poste:
    image: analogic/poste.io
    restart: always
    ports:
      - 443:443
      - 80:80
    expose:
      - 25
      - 80
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - ./mail:/data
    networks:
      - default
    environment:
      - HTTPS_PORT=4443
      - HTTP_PORT=8181
      - DISABLE_CLAMAV=TRUE
